version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${DATABASE}

  db:
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email your-email@example.com --agree-tos --no-eff-email --staging -d your-domain.com
