version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=030118032
      - MARIADB_DATABASE=final

  db:
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=YAM428
      - MYSQL_USER=030118032
      - MYSQL_PASSWORD=final

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email eryaz.hakan@std.izu.edu.tr --agree-tos --no-eff-email -d 137.117.191.35
